# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nur_Umra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'Alamofire'
 pod 'lottie-ios'
 pod 'SwiftyJSON'
 pod 'ImageSlideshow/SDWebImage'
 pod 'GoogleMaps'
 pod 'GooglePlaces'
 pod 'Localize-Swift', '~> 3.2'
 pod 'SnapKit'

end
